#!/usr/bin/env node
// Scans installed node_modules for each dependency's declared license and writes
// docs/DEPENDENCY-LICENSES.md. Zero extra dependencies — just reads package.json
// files. Run: npm run licenses
import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const nm = join(root, "node_modules");

/** Read one package's name/version/license, tolerating malformed manifests. */
function readPkg(dir) {
  const p = join(dir, "package.json");
  if (!existsSync(p)) return null;
  try {
    const j = JSON.parse(readFileSync(p, "utf8"));
    if (!j.name) return null;
    const license =
      typeof j.license === "string"
        ? j.license
        : j.license?.type ?? (Array.isArray(j.licenses) ? j.licenses.map((l) => l.type).join(" OR ") : "UNKNOWN");
    return { name: j.name, version: j.version ?? "?", license: license || "UNKNOWN" };
  } catch {
    return null;
  }
}

function collect() {
  const out = new Map();
  if (!existsSync(nm)) return out;
  for (const entry of readdirSync(nm)) {
    if (entry.startsWith(".")) continue;
    const dir = join(nm, entry);
    if (!statSync(dir).isDirectory()) continue;
    if (entry.startsWith("@")) {
      // scoped: iterate the scope's packages
      for (const sub of readdirSync(dir)) {
        const pkg = readPkg(join(dir, sub));
        if (pkg) out.set(pkg.name, pkg);
      }
    } else {
      const pkg = readPkg(dir);
      if (pkg) out.set(pkg.name, pkg);
    }
  }
  return out;
}

const pkgs = [...collect().values()].sort((a, b) => a.name.localeCompare(b.name));
const byLicense = new Map();
for (const p of pkgs) byLicense.set(p.license, (byLicense.get(p.license) ?? 0) + 1);

const lines = [];
lines.push("# Third-party dependency licenses");
lines.push("");
lines.push("Auto-generated by `npm run licenses` from installed `node_modules`. Regenerate after dependency changes. Workspace-internal `@finesign/*` / `finesign-core` packages are the project's own code (Apache-2.0).");
lines.push("");
lines.push("## Summary");
lines.push("");
lines.push("| License | Packages |");
lines.push("| --- | ---: |");
for (const [lic, n] of [...byLicense.entries()].sort((a, b) => b[1] - a[1])) {
  lines.push(`| ${lic} | ${n} |`);
}
lines.push("");
lines.push(`Total: **${pkgs.length}** installed packages.`);
lines.push("");
lines.push("## All packages");
lines.push("");
lines.push("| Package | Version | License |");
lines.push("| --- | --- | --- |");
for (const p of pkgs) {
  lines.push(`| ${p.name} | ${p.version} | ${p.license} |`);
}
lines.push("");

// Flag anything that isn't a common permissive license, for a human to review.
const PERMISSIVE = /^(MIT|ISC|BSD|Apache|0BSD|Unlicense|CC0|CC-BY|Python|BlueOak|WTFPL|MIT-0)/i;
const flagged = pkgs.filter((p) => p.license === "UNKNOWN" || !PERMISSIVE.test(p.license));
if (flagged.length) {
  lines.push("## ⚠️ Review (non-permissive or unknown)");
  lines.push("");
  lines.push("| Package | Version | License |");
  lines.push("| --- | --- | --- |");
  for (const p of flagged) lines.push(`| ${p.name} | ${p.version} | ${p.license} |`);
  lines.push("");
}

writeFileSync(join(root, "docs", "DEPENDENCY-LICENSES.md"), lines.join("\n"));
console.log(`Wrote docs/DEPENDENCY-LICENSES.md — ${pkgs.length} packages, ${flagged.length} flagged for review.`);
if (flagged.length) {
  console.log("Flagged:");
  for (const p of flagged) console.log(`  ${p.name}@${p.version}: ${p.license}`);
}
